name: Kudos Pull Request Action

on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  pr-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node v20
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Check Versions
        run: |
          node -v
          bun -v

      - name: Bun Install
        run: bun install

      - name: Diff Check
        run: bun diff-exit-code

      - name: Prettier Check
        run: bun prettier:check

      - name: Typescript Check
        run: bun typescript

      - name: ESlint
        run: bun lint

      - name: Test
        run: bun test

      - name: Build
        run: bun run build

      - name: Diff Check
        run: bun diff-exit-code
